services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: datagurudatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Bsu2019!
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:Bsu2019!@db:5432/datagurudatabase    
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
